### ISSUE TITLE
Can't import PlexInfluxdbCollector

### ISSUE THREAD

**Issue by andloh** [barrycarey/Plex-Data-Collector-For-InfluxDB#23]
When running plexcollector.py:
ubuntu server 17.10
python 3 installed

ModuleNotFoundError: No module named 'plexcollector.PlexInfluxdbCollector'; 'plexcollector' is not a package

**Comment by barrycarey** [comment]
How are you launching it?

**Comment by andloh** [comment]
Python3 plexcollector.py

**Comment by barrycarey** [comment]
I just spun up a Ubuntu 17.10 VM and can't replicate this.   It worked straight away.  Try delete everything and clone it from here again. 

![image](https://user-images.githubusercontent.com/3161456/46905081-39946480-cebc-11e8-8815-0dfa95ed33ca.png)

**Comment by andloh** [comment]
Hm, Ok. I tried on another ubuntu instance. Then I get this error....requirements are installed: 

xxx@xxx~/Plex-Data-Collector-For-InfluxDB$ python3 plexcollector.py
Traceback (most recent call last):
  File "plexcollector.py", line 3, in <module>
    from plexcollector.PlexInfluxdbCollector import PlexInfluxdbCollector
  File "/home/xxx/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 9, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'

**Comment by svindled** [comment]
@andloh 
There is definitely some tribal knowledge with setting up the python environment aside from just having python3 installed.

The packages installed by PIP need to exist in the python3 environment which by installing pip via `sudo apt install python-pip` installs it for python2.7 rather than 3.

What needs to be installed is the python3 version of PIP. This can be done by running `sudo apt install python3-pip` and then installing the requirements by running `sudo pip3 install -r requirements.txt`

Hope this helps.
